SP: Attempt to fix GetString() calls with cvars in ICARUS
JACoders/OpenJK pull request #1139
Opened 2023-03-01 03:20 UTC by ensiform

Cvar_VariableStringBuffer() does not like unallocated buffers with strlen().

Uses a local variable and cache the result in a map<> that is then cleared upon shutdown.

2023-03-28 11:54 UTC, mrwonko commented
Adding a cache feels weird. Caches usually make things more complicated. I'm not familiar enough with the code to tell if they're necessary at a quick glance, I need to study the code in detail first.

How do I reproduce the issue this fixes?

2023-03-28 16:22 UTC, AntiAnti commented
> Adding a cache feels weird. Caches usually make things more complicated. I'm not familiar enough with the code to tell if they're necessary at a quick glance, I need to study the code in detail first.
> 
> How do I reproduce the issue this fixes?

Read any cvar in script. For example:
`print ( $get( STRING, "cvar_g_char_model")$ );`

There is another possible, simplier fix for this bug, but it wouldn't work for two cvar requests in the same expression (for example, in the IF expression). Not critical, as for me.
```
// Q3_Interface.cpp, CQuake3GameInterface::GetString, line 10571
if( strlen(name) > 5 &&
	Q_stricmpn(name, "cvar_", 5) )
{
	static char cvarbuf[MAX_STRING_CHARS];

	// save in static buffer rather then NULL pointer
	gi.Cvar_VariableStringBuffer(name+5, cvarbuf, sizeof(cvarbuf));
	*value = cvarbuf;
	return true;
}
```

I need to fix this bug for my mod, which is almost done now.

2023-03-28 17:19 UTC, mrwonko approved these changes
This should fix the issue it tries to, and doesn't really do anything wrong, even if it feels a bit weird to copy the value.

2023-03-28 19:09 UTC, ensiform commented
Are you saying the cache code still crashes?

The point of the cache code is to not reuse one buffer and clobber over it in cases of multiple calls.

2023-03-28 21:15 UTC, mrwonko commented
> Are you saying the cache code still crashes?

No, just that caches are naturally complex and best avoided. But given the constraints, it's acceptable here, it doesn't prevent re-evaluation, it's just a form of memory management.

2023-03-28 22:19 UTC, ensiform commented on code/game/Q3_Interface.cpp
> +		*value = &m_cvars[name+5][0];
That very well may be, but as I don't have scripts that can vigorously test the corner cases and such hard to say. and I don't really feel like putting in the time to do so either lol

2023-03-29 06:16 UTC, mrwonko commented on code/game/Q3_Interface.cpp
> +		*value = &m_cvars[name+5][0];
I'll give it another look tonight.

2023-03-29 09:36 UTC, mrwonko requested changes
The potential use-after-free scares me, I'll take a stab at fixing it later

2023-03-29 18:59 UTC, mrwonko commented on code/game/Q3_Interface.cpp
> +		*value = &m_cvars[name+5][0];
I've fixed it by replacing the `std::string` map values with fixed-size buffers, which then get re-used on subsequent calls, so the pointers never become invalid.

2023-03-29 19:02 UTC, mrwonko commented on code/game/Q3_Interface.cpp
> +#include <array>
I'm not entirely sure about the right place to include <array> according to q3 conventions, so I used normal c++ best practices and only included it in the .cpp that actually needs it

2023-03-31 07:05 UTC, mrwonko approved these changes

2023-04-03 07:41 UTC, mrwonko commented
I've formally approved this, but since I also contributed code changes I'd prefer a second opinion before we merge

2023-04-05 18:23 UTC, bartrpe approved these changes

2023-04-05 20:14 UTC, ensiform commented
Go ahead

2023-04-16 07:07 UTC, merged